/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dangnhap;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author ddoox
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_DangNhap = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_DangNhapBangFacebook = new javax.swing.JButton();
        jButton_DangNhapBangGoogle = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_NhapHoTen = new javax.swing.JTextField();
        jTextField_NhapSoDienThoai = new javax.swing.JTextField();
        jTextField_NhapEmail = new javax.swing.JTextField();
        jCheckBox_XacNhan = new javax.swing.JCheckBox();
        jButton_DangKy = new javax.swing.JButton();
        jPasswordField_NhapMatKhau = new javax.swing.JPasswordField();
        jLabel_ErrorHoTen = new javax.swing.JLabel();
        jLabel_ErrorSoDienThoai = new javax.swing.JLabel();
        jLabel_ErrorMatKhau = new javax.swing.JLabel();
        jLabel_ErrorEmail = new javax.swing.JLabel();
        jCheckBox_HienMatKhau = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ađâyrồi");

        jButton_DangNhap.setText("Đăng nhập");
        jButton_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DangNhapActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Đăng ký miễn phí");

        jLabel3.setText("Dễ dàng truy cập lịch sử đơn hàng, ");

        jButton_DangNhapBangFacebook.setBackground(new java.awt.Color(51, 51, 255));
        jButton_DangNhapBangFacebook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_DangNhapBangFacebook.setForeground(new java.awt.Color(255, 255, 255));
        jButton_DangNhapBangFacebook.setText("Đăng nhập bằng Facebook");
        jButton_DangNhapBangFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DangNhapBangFacebookActionPerformed(evt);
            }
        });

        jButton_DangNhapBangGoogle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_DangNhapBangGoogle.setText("Đăng nhập bằng Google");
        jButton_DangNhapBangGoogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DangNhapBangGoogleActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Họ và tên");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Số điện thoại");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Mật khẩu");

        jTextField_NhapHoTen.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_NhapHoTen.setText("Nhập họ và tên");
        jTextField_NhapHoTen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_NhapHoTenFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_NhapHoTenFocusLost(evt);
            }
        });

        jTextField_NhapSoDienThoai.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_NhapSoDienThoai.setText("Nhập số điện thoại");
        jTextField_NhapSoDienThoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_NhapSoDienThoaiFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_NhapSoDienThoaiFocusLost(evt);
            }
        });

        jTextField_NhapEmail.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_NhapEmail.setText("Nhập email");
        jTextField_NhapEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_NhapEmailFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_NhapEmailFocusLost(evt);
            }
        });

        jCheckBox_XacNhan.setText("Tôi muốn nhận thông tin khuyến mại và ưu đãi");
        jCheckBox_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_XacNhanActionPerformed(evt);
            }
        });

        jButton_DangKy.setText("Đăng ký");
        jButton_DangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DangKyActionPerformed(evt);
            }
        });

        jPasswordField_NhapMatKhau.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_NhapMatKhau.setText("Nhập mật khẩu");
        jPasswordField_NhapMatKhau.setEchoChar('\u0000');
        jPasswordField_NhapMatKhau.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_NhapMatKhauFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_NhapMatKhauFocusLost(evt);
            }
        });

        jCheckBox_HienMatKhau.setText("Hiện mật khẩu");
        jCheckBox_HienMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_HienMatKhauActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(
                "C:\\Users\\ddoox\\Documents\\java\\Dangnhap\\src\\main\\java\\images\\Hinh_app.png")); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jButton_DangNhapBangGoogle,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton_DangNhapBangFacebook,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 115,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jButton_DangNhap)))
                                                .addGap(10, 10, 10))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jCheckBox_XacNhan,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 283,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(31, 31, 31)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                        .addComponent(jPasswordField_NhapMatKhau)
                                                                        .addComponent(jTextField_NhapHoTen,
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel_ErrorHoTen,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jTextField_NhapSoDienThoai,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                178, Short.MAX_VALUE)
                                                                        .addComponent(jLabel_ErrorSoDienThoai,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel_ErrorMatKhau,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jTextField_NhapEmail,
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel_ErrorEmail,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(73, 73, 73)
                                                                .addComponent(jButton_DangKy,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 114,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(154, 154, 154)
                                                                .addComponent(jCheckBox_HienMatKhau)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        113, Short.MAX_VALUE)))
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 783,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton_DangNhap))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton_DangNhapBangFacebook)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton_DangNhapBangGoogle)
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_NhapHoTen,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(jLabel5))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel_ErrorHoTen)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_NhapSoDienThoai,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(jLabel6)
                                                                .addGap(3, 3, 3))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel1Layout.createSequentialGroup()
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jLabel_ErrorSoDienThoai)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                                .addComponent(jTextField_NhapEmail,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)
                                                .addComponent(jLabel_ErrorEmail)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPasswordField_NhapMatKhau,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel_ErrorMatKhau)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jCheckBox_HienMatKhau)
                                                .addGap(8, 8, 8)
                                                .addComponent(jCheckBox_XacNhan)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton_DangKy))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel8)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_DangNhapActionPerformed
        // TODO add your handling code here:
        DangNhappppp dangNhapFrame = new DangNhappppp();
        dangNhapFrame.setVisible(true); // Hiển thị JFrame mới

        // Làm mờ JFrame hiện tại
        this.setOpacity(0.5f); // Đặt độ mờ của JFrame hiện tại

        // Thêm sự kiện để khôi phục độ mờ khi JFrame mới đóng
        dangNhapFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                setOpacity(1.0f); // Khôi phục JFrame hiện tại về trạng thái bình thường
            }
        });

    }// GEN-LAST:event_jButton_DangNhapActionPerformed

    private void jButton_DangNhapBangFacebookActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_DangNhapBangFacebookActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Đăng nhập bằng Facebook thành công!", "Thông báo",
                JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_jButton_DangNhapBangFacebookActionPerformed

    private void jCheckBox_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox_XacNhanActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jCheckBox_XacNhanActionPerformed

    private void jTextField_NhapHoTenFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField_NhapHoTenFocusGained
        // TODO add your handling code here:
        if (jTextField_NhapHoTen.getText().equals("Nhập họ và tên")) {
            jTextField_NhapHoTen.setText("");
            jTextField_NhapHoTen.setForeground(new Color(0, 0, 0));
        }
    }// GEN-LAST:event_jTextField_NhapHoTenFocusGained

    private void jTextField_NhapHoTenFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField_NhapHoTenFocusLost
        // TODO add your handling code here:
        if (jTextField_NhapHoTen.getText().equals("")) {
            jTextField_NhapHoTen.setText("Nhập họ và tên");
            jTextField_NhapHoTen.setForeground(new Color(153, 153, 153));
        }
    }// GEN-LAST:event_jTextField_NhapHoTenFocusLost

    private void jTextField_NhapSoDienThoaiFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField_NhapSoDienThoaiFocusGained
        // TODO add your handling code here:
        if (jTextField_NhapSoDienThoai.getText().equals("Nhập số điện thoại")) {
            jTextField_NhapSoDienThoai.setText("");
            jTextField_NhapSoDienThoai.setForeground(new Color(0, 0, 0));
        }
    }// GEN-LAST:event_jTextField_NhapSoDienThoaiFocusGained

    private void jTextField_NhapSoDienThoaiFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField_NhapSoDienThoaiFocusLost
        // TODO add your handling code here:
        if (jTextField_NhapSoDienThoai.getText().equals("")) {
            jTextField_NhapSoDienThoai.setText("Nhập số điện thoại");
            jTextField_NhapSoDienThoai.setForeground(new Color(153, 153, 153));
        }
    }// GEN-LAST:event_jTextField_NhapSoDienThoaiFocusLost

    private void jTextField_NhapEmailFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField_NhapEmailFocusGained
        // TODO add your handling code here:
        if (jTextField_NhapEmail.getText().equals("Nhập email")) {
            jTextField_NhapEmail.setText("");
            jTextField_NhapEmail.setForeground(new Color(0, 0, 0));
        }
    }// GEN-LAST:event_jTextField_NhapEmailFocusGained

    private void jTextField_NhapEmailFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextField_NhapEmailFocusLost
        // TODO add your handling code here:
        if (jTextField_NhapEmail.getText().equals("")) {
            jTextField_NhapEmail.setText("Nhập email");
            jTextField_NhapEmail.setForeground(new Color(153, 153, 153));
        }
    }// GEN-LAST:event_jTextField_NhapEmailFocusLost

    private void jPasswordField_NhapMatKhauFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jPasswordField_NhapMatKhauFocusGained
        // TODO add your handling code here:
        if (String.valueOf(jPasswordField_NhapMatKhau.getPassword()).equals("Nhập mật khẩu")) {
            jPasswordField_NhapMatKhau.setText("");
            jPasswordField_NhapMatKhau.setEchoChar('\u2022');
            jPasswordField_NhapMatKhau.setForeground(new Color(0, 0, 0));
        }
    }// GEN-LAST:event_jPasswordField_NhapMatKhauFocusGained

    private void jPasswordField_NhapMatKhauFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jPasswordField_NhapMatKhauFocusLost
        // TODO add your handling code here:
        if (String.valueOf(jPasswordField_NhapMatKhau.getPassword()).equals("")) {
            jPasswordField_NhapMatKhau.setText("Nhập mật khẩu");
            jPasswordField_NhapMatKhau.setEchoChar('\u0000');
            jPasswordField_NhapMatKhau.setForeground(new Color(153, 153, 153));
        }
    }// GEN-LAST:event_jPasswordField_NhapMatKhauFocusLost

    private boolean kiemTraEmailHopLe(String email) {
        if (email == null || email.isEmpty()) {
            return false;
        }
        int atIndex = email.indexOf('@');
        int dotIndex = email.lastIndexOf('.');

        // Kiểm tra '@' tồn tại, dấu '.' nằm sau '@', và không nằm ở đầu hoặc cuối.
        if (atIndex > 0 && dotIndex > atIndex + 1 && dotIndex < email.length() - 1) {
            return true;
        }
        return false;
    }

    private boolean kiemTraSoDienThoaiHopLe(String soDienThoai) {
        if (soDienThoai == null || soDienThoai.isEmpty()) {
            return false;
        }
        if (soDienThoai.length() < 9 || soDienThoai.length() > 11) {
            return false;
        }
        for (char c : soDienThoai.toCharArray()) {
            if (!Character.isDigit(c)) {
                return false;
            }
        }
        return true;
    }

    private boolean kiemTraMatKhauHopLe(String matKhau) {
        if (matKhau == null || matKhau.isEmpty() || matKhau.length() < 8) {
            return false;
        }
        boolean hasLower = false;
        boolean hasUpper = false;
        boolean hasDigit = false;
        boolean hasSpecial = false;
        String specialCharacters = "@$!%*?&";

        for (char c : matKhau.toCharArray()) {
            if (Character.isLowerCase(c)) {
                hasLower = true;
            } else if (Character.isUpperCase(c)) {
                hasUpper = true;
            } else if (Character.isDigit(c)) {
                hasDigit = true;
            } else if (specialCharacters.indexOf(c) != -1) {
                hasSpecial = true;
            }
        }
        return hasLower && hasUpper && hasDigit && hasSpecial;
    }

    private boolean validateFields() {
        Border redBorder = BorderFactory.createLineBorder(Color.RED, 2);
        boolean isValid = true;

        // Kiểm tra Họ và Tên
        if (jTextField_NhapHoTen.getText().equals("") || jTextField_NhapHoTen.getText().equals("Nhập họ và tên")) {
            jTextField_NhapHoTen.setBorder(redBorder);
            jLabel_ErrorHoTen.setText("Vui lòng điền thông tin");
            isValid = false;
        } else {
            jTextField_NhapHoTen.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
            jLabel_ErrorHoTen.setText("");
        }

        // Kiểm tra Số Điện Thoại
        String soDienThoai = jTextField_NhapSoDienThoai.getText();
        if (soDienThoai.equals("") || soDienThoai.equals("Nhập số điện thoại")) {
            jTextField_NhapSoDienThoai.setBorder(redBorder);
            jLabel_ErrorSoDienThoai.setText("Vui lòng điền thông tin");
            isValid = false;
        } else if (!kiemTraSoDienThoaiHopLe(soDienThoai)) {
            jTextField_NhapSoDienThoai.setBorder(redBorder);
            jLabel_ErrorSoDienThoai.setText("Số điện thoại không hợp lệ!");
            isValid = false;
        } else {
            jTextField_NhapSoDienThoai.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
            jLabel_ErrorSoDienThoai.setText("");
        }

        // Kiểm tra Email
        String email = jTextField_NhapEmail.getText();
        if (email.equals("Nhập email")) {
            email = null;
        }
        if (email != null && !kiemTraEmailHopLe(email)) {
            jTextField_NhapEmail.setBorder(redBorder);
            jLabel_ErrorEmail.setText("Email không hợp lệ!");
            isValid = false;
        } else {
            jTextField_NhapEmail.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
            jLabel_ErrorEmail.setText("");
        }

        // Kiểm tra Mật Khẩu
        String matKhau = String.valueOf(jPasswordField_NhapMatKhau.getPassword());
        if (matKhau.equals("") || matKhau.equals("Nhập mật khẩu")) {
            jPasswordField_NhapMatKhau.setBorder(redBorder);
            jLabel_ErrorMatKhau.setText("Vui lòng điền thông tin");
            isValid = false;
        } else if (!kiemTraMatKhauHopLe(matKhau)) {
            jPasswordField_NhapMatKhau.setBorder(redBorder);
            jLabel_ErrorMatKhau
                    .setText("Mật khẩu phải có ít nhất 8 ký tự, bao gồm chữ hoa, chữ thường, số và ký tự đặc biệt.");
            isValid = false;
        } else {
            jPasswordField_NhapMatKhau.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
            jLabel_ErrorMatKhau.setText("");
        }

        return isValid;
    }

    private void jButton_DangKyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_DangKyActionPerformed
        // TODO add your handling code here:

        if (!validateFields()) {
            JOptionPane.showMessageDialog(this, "Thông tin nhập không hợp lệ. Vui lòng kiểm tra lại!", "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String hoTen = jTextField_NhapHoTen.getText();
        String soDienThoai = jTextField_NhapSoDienThoai.getText();
        String email = jTextField_NhapEmail.getText();
        if (email.equals("Nhập email")) {
            email = null;
        }
        String matKhau = new String(jPasswordField_NhapMatKhau.getPassword());

        boolean isChecked = jCheckBox_XacNhan.isSelected();
        String xacNhanKhuyenMai = isChecked ? "Có" : "Không";

        Connection ketNoi = KetNoiCSDL.layKetNoi();
        String sql = "INSERT INTO UserTable (HoVaTen, SoDienThoai, Email, MatKhau, XacNhanKhuyenMai) VALUES (?, ?, ?, ?, ?)";

        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1, hoTen);
            ps.setString(2, soDienThoai);
            ps.setString(3, email);
            ps.setString(4, matKhau);
            ps.setString(5, xacNhanKhuyenMai);
            ps.executeUpdate();
            ps.close();
            ketNoi.close();
            JOptionPane.showMessageDialog(this, "Đăng ký thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE,
                    "Lỗi khi thực thi câu lệnh SQL: " + ex.getMessage(), ex);
            System.out.println("Lỗi khi đăng ký: " + ex.getMessage());
        }
    }// GEN-LAST:event_jButton_DangKyActionPerformed

    private void jButton_DangNhapBangGoogleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_DangNhapBangGoogleActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Đăng nhập bằng Google thành công!", "Thông báo",
                JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_jButton_DangNhapBangGoogleActionPerformed

    private void jCheckBox_HienMatKhauActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox_HienMatKhauActionPerformed
        // TODO add your handling code here:
        if (jCheckBox_HienMatKhau.isSelected()) {
            jPasswordField_NhapMatKhau.setEchoChar((char) 0);
        } else {
            jPasswordField_NhapMatKhau.setEchoChar('\u2022');
        }
    }// GEN-LAST:event_jCheckBox_HienMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DangKy;
    private javax.swing.JButton jButton_DangNhap;
    private javax.swing.JButton jButton_DangNhapBangFacebook;
    private javax.swing.JButton jButton_DangNhapBangGoogle;
    private javax.swing.JCheckBox jCheckBox_HienMatKhau;
    private javax.swing.JCheckBox jCheckBox_XacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_ErrorEmail;
    private javax.swing.JLabel jLabel_ErrorHoTen;
    private javax.swing.JLabel jLabel_ErrorMatKhau;
    private javax.swing.JLabel jLabel_ErrorSoDienThoai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_NhapMatKhau;
    private javax.swing.JTextField jTextField_NhapEmail;
    private javax.swing.JTextField jTextField_NhapHoTen;
    private javax.swing.JTextField jTextField_NhapSoDienThoai;
    // End of variables declaration//GEN-END:variables
}
