/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dangnhap;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author ddoox
 */
public class DangNhappppp extends javax.swing.JFrame {

    /**
     * Creates new form DangNhappppp
     */
    public DangNhappppp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_SDT = new javax.swing.JTextField();
        jPasswordField_MatKhau = new javax.swing.JPasswordField();
        jButton_DangNhap = new javax.swing.JButton();
        jCheckBox_HienMatKhau = new javax.swing.JCheckBox();
        jLabel_ErrorSDT = new javax.swing.JLabel();
        jLabel_ErrorMatKhau = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Đăng nhập");

        jLabel2.setText("Số điện thoại");

        jLabel3.setText("Mật khẩu");

        jTextField_SDT.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_SDT.setText("Nhập số điện thoại");
        jTextField_SDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_SDTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_SDTFocusLost(evt);
            }
        });

        jPasswordField_MatKhau.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_MatKhau.setText("Nhập mật khẩu");
        jPasswordField_MatKhau.setEchoChar('\u0000');
        jPasswordField_MatKhau.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_MatKhauFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_MatKhauFocusLost(evt);
            }
        });

        jButton_DangNhap.setText("Đăng nhập");
        jButton_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DangNhapActionPerformed(evt);
            }
        });

        jCheckBox_HienMatKhau.setText("Hiện mật khẩu");
        jCheckBox_HienMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_HienMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jButton_DangNhap))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_ErrorSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_SDT)
                            .addComponent(jPasswordField_MatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jLabel_ErrorMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(223, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 220, Short.MAX_VALUE)
                .addComponent(jCheckBox_HienMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel_ErrorSDT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_ErrorMatKhau)
                .addGap(17, 17, 17)
                .addComponent(jCheckBox_HienMatKhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_DangNhap)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validateFields(){
        Border redBorder = BorderFactory.createLineBorder(Color.RED, 2);
        boolean isValid = true;
        String soDienThoai = jTextField_SDT.getText();
        if (soDienThoai.equals("") || soDienThoai.equals("Nhập số điện thoại")) {
            jTextField_SDT.setBorder(redBorder);
            jLabel_ErrorSDT.setText("Vui lòng điền thông tin");
            isValid = false;
        } else {
            jTextField_SDT.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
            jLabel_ErrorSDT.setText("");
        }
        
        String matKhau = String.valueOf(jPasswordField_MatKhau.getPassword());
        if (matKhau.equals("") || matKhau.equals("Nhập mật khẩu")) {
            jPasswordField_MatKhau.setBorder(redBorder);
            jLabel_ErrorMatKhau.setText("Vui lòng điền thông tin");
            isValid = false;
        } else {
            jPasswordField_MatKhau.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
            jLabel_ErrorMatKhau.setText("");
        }

        return isValid;
    
    }
    
    
    private void jButton_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DangNhapActionPerformed
        // TODO add your handling code here:
        if (!validateFields()) {
            JOptionPane.showMessageDialog(this, "Thông tin nhập không hợp lệ. Vui lòng kiểm tra lại!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
    }
        String soDienThoai = jTextField_SDT.getText();
        String password = new String(jPasswordField_MatKhau.getPassword());

        try {
        
        Connection ketNoi = KetNoiCSDL.layKetNoi();
        String sql = "select * from UserTable where SoDienThoai = ? and MatKhau = ?";
        
        PreparedStatement pst = ketNoi.prepareStatement(sql);
        pst.setString(1, soDienThoai);
        pst.setString(2, password);

        // 3. Thực thi truy vấn
        ResultSet rs = pst.executeQuery();

        // 4. Kiểm tra kết quả
        if (rs.next()) { // Nếu có kết quả
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            
            // Mở JFrame mới
            DangNhap dangNhapFrame = new DangNhap();
            dangNhapFrame.setVisible(true);
            this.dispose(); // Đóng JFrame hiện tại (nếu cần)
        } else {
            JOptionPane.showMessageDialog(this, "Số điện thoại hoặc mật khẩu không chính xác!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
            rs.close();
            pst.close();
            ketNoi.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton_DangNhapActionPerformed

    private void jCheckBox_HienMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_HienMatKhauActionPerformed
        // TODO add your handling code here:
        if (jCheckBox_HienMatKhau.isSelected()){
            jPasswordField_MatKhau.setEchoChar((char)0);
        }
        else{
            jPasswordField_MatKhau.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_jCheckBox_HienMatKhauActionPerformed

    private void jTextField_SDTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_SDTFocusGained
        // TODO add your handling code here:
        if(jTextField_SDT.getText().equals("Nhập số điện thoại")){
            jTextField_SDT.setText("");
            jTextField_SDT.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jTextField_SDTFocusGained

    private void jTextField_SDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_SDTFocusLost
        // TODO add your handling code here:
        if(jTextField_SDT.getText().equals("")){
            jTextField_SDT.setText("Nhập số điện thoại");
            jTextField_SDT.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextField_SDTFocusLost

    private void jPasswordField_MatKhauFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_MatKhauFocusGained
        // TODO add your handling code here:
        if(String.valueOf(jPasswordField_MatKhau.getPassword()).equals("Nhập mật khẩu")){
            jPasswordField_MatKhau.setText("");
            jPasswordField_MatKhau.setEchoChar('\u2022');
            jPasswordField_MatKhau.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jPasswordField_MatKhauFocusGained

    private void jPasswordField_MatKhauFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_MatKhauFocusLost
        // TODO add your handling code here:
        if(String.valueOf(jPasswordField_MatKhau.getPassword()).equals("")){
            jPasswordField_MatKhau.setText("Nhập mật khẩu");
            jPasswordField_MatKhau.setEchoChar('\u0000');
            jPasswordField_MatKhau.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jPasswordField_MatKhauFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhappppp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhappppp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhappppp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhappppp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhappppp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DangNhap;
    private javax.swing.JCheckBox jCheckBox_HienMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_ErrorMatKhau;
    private javax.swing.JLabel jLabel_ErrorSDT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_MatKhau;
    private javax.swing.JTextField jTextField_SDT;
    // End of variables declaration//GEN-END:variables
}
