
package com.mycompany.qlsv2;

import java.sql.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.util.*;

public class QLSV2 extends javax.swing.JFrame {

    /**
     * Creates new form QLSV2
     */
    public QLSV2() {
        initComponents();
        layThongTinSach();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTieuDe = new javax.swing.JLabel();
        jLabelChucNang = new javax.swing.JLabel();
        jLabelThongTin1 = new javax.swing.JLabel();
        jLabelTuaSach = new javax.swing.JLabel();
        jLabelMaSach1 = new javax.swing.JLabel();
        jLabelTacGia = new javax.swing.JLabel();
        jLabelNXB = new javax.swing.JLabel();
        jTextFieldMaSach = new javax.swing.JTextField();
        jTextFieldTuaSach = new javax.swing.JTextField();
        jTextFieldTacGia = new javax.swing.JTextField();
        jTextFieldNXB = new javax.swing.JTextField();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonLamLai = new javax.swing.JButton();
        jButtonThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBangSach = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTieuDe.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTieuDe.setText("DANH SÁCH CÁC ĐẦU SÁCH TRONG THƯ VIỆN");

        jLabelChucNang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelChucNang.setText("Chức Năng");

        jLabelThongTin1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelThongTin1.setText("Thông Tin");

        jLabelTuaSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTuaSach.setText("Tựa Sách");

        jLabelMaSach1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMaSach1.setText("Mã Sách");

        jLabelTacGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTacGia.setText("Tác Giả");

        jLabelNXB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNXB.setText("Nhà Xuất Bản");

        jTextFieldTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTacGiaActionPerformed(evt);
            }
        });

        jTextFieldNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNXBActionPerformed(evt);
            }
        });

        jButtonThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButtonSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jButtonXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonXoa.setText("Xóa");
        jButtonXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonXoaMouseClicked(evt);
            }
        });
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jButtonLamLai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonLamLai.setText("Làm Lại");
        jButtonLamLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLamLaiActionPerformed(evt);
            }
        });

        jButtonThoat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });

        jTableBangSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ SÁCH", "TỰA SÁCH", "TÁC GIẢ", "NHÀ XUẤT BẢN"
            }
        ));
        jScrollPane1.setViewportView(jTableBangSach);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabelTuaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldTuaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jButtonLamLai, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jButtonThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(153, 153, 153)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(jTextFieldTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(jLabelThongTin1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(736, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(jLabelMaSach1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(758, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelTieuDe)
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTacGia)
                    .addComponent(jTextFieldMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNXB)
                            .addComponent(jTextFieldNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTuaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTuaSach))))
                .addGap(42, 42, 42)
                .addComponent(jLabelChucNang)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThem)
                    .addComponent(jButtonSua)
                    .addComponent(jButtonXoa)
                    .addComponent(jButtonLamLai)
                    .addComponent(jButtonThoat))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(jLabelThongTin1)
                    .addContainerGap(485, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(159, 159, 159)
                    .addComponent(jLabelMaSach1)
                    .addContainerGap(437, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTacGiaActionPerformed

    private void jTextFieldNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNXBActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
         int selectedRow = jTableBangSach.getSelectedRow();

        if (selectedRow == -1) { // Nếu không có hàng nào được chọn
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng để xóa!");
            return;
        }

         // Lấy dữ liệu của hàng được chọn
        String maSach = (String) jTableBangSach.getValueAt(selectedRow, 0); // Cột MASACH
        String tuaSach = (String) jTableBangSach.getValueAt(selectedRow, 1); // Cột TUASACH
        String tacGia = (String) jTableBangSach.getValueAt(selectedRow, 2); // Cột TACGIA
        String nhaXuatBan = (String) jTableBangSach.getValueAt(selectedRow, 3); // Cột NHAXUATBAN

        // Hiển thị hộp thoại xác nhận
        int confirm = JOptionPane.showConfirmDialog(
            null,
            "Bạn có chắc chắn muốn xóa sách này?\n" +
            "- Mã sách: " + maSach + "\n" +
            "- Tựa sách: " + tuaSach + "\n" +
            "- Tác giả: " + tacGia + "\n" +
            "- Nhà xuất bản: " + nhaXuatBan,
            "Xác nhận xóa",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            // Thực hiện xóa sách trong cơ sở dữ liệu
            Connection ketNoi = KetNoiCSDL.layKetNoi();
            String sql = "DELETE FROM SACH WHERE MASACH = ?";
            try {
                PreparedStatement ps = ketNoi.prepareStatement(sql);
                ps.setString(1, maSach); // Gán giá trị MASACH vào câu lệnh DELETE
                int rowsAffected = ps.executeUpdate(); // Thực thi lệnh DELETE

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Xóa thành công!");

                    // Xóa hàng khỏi giao diện
                    DefaultTableModel model = (DefaultTableModel) jTableBangSach.getModel();
                    model.removeRow(selectedRow); // Xóa hàng được chọn khỏi bảng
                } else {
                    JOptionPane.showMessageDialog(null, "Không tìm thấy sách để xóa!");
                }

                ps.close();
                ketNoi.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Lỗi khi xóa sách: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonLamLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLamLaiActionPerformed
        jTextFieldMaSach.setText("");
        jTextFieldTuaSach.setText("");
        jTextFieldTacGia.setText("");
        jTextFieldNXB.setText("");
    }//GEN-LAST:event_jButtonLamLaiActionPerformed

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        int luaChon = JOptionPane.showConfirmDialog(this, "Bạn có thực sự muốn thoát khỏi cửa sổ này?", "Hỏi",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(luaChon == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        String maSach = jTextFieldMaSach.getText().trim();
        String tuaSach = jTextFieldTuaSach.getText().trim();
        String tacGia = jTextFieldTacGia.getText().trim();
        String NXB = jTextFieldNXB.getText().trim();
        
        if(maSach.isEmpty() || tuaSach.isEmpty()  || tacGia.isEmpty()  || NXB.isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui long dien day du thong tin!" , "Yêu cầu", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Connection ketNoi = KetNoiCSDL.layKetNoi();
        String ktMa = "select count(*) from SACH where MASACH = ?";
        String luuSach = "insert into SACH (MASACH, TUASACH, TACGIA, NHAXUATBAN) values (?, ?, ?, ?)";
        
        try{
        PreparedStatement kt = ketNoi.prepareStatement(ktMa);
        kt.setString(1, maSach);
        ResultSet rs = kt.executeQuery();
        
        if(rs.next() && rs.getInt(1) > 0){
            JOptionPane.showMessageDialog(this, "Ma sach da ton tai! Vui long dien ma sach khac!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            kt.close();
            rs.close();
            return;
        }
        
       PreparedStatement luu = ketNoi.prepareStatement(luuSach);
       luu.setString(1, maSach);
       luu.setString(2, tuaSach);
       luu.setString(3, tacGia);
       luu.setString(4, NXB);
       
       int thongBao = luu.executeUpdate();
       
       if(thongBao > 0){
           JOptionPane.showMessageDialog(this, "Thêm sách thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
           layThongTinSach();
          
       }
       else{
           JOptionPane.showMessageDialog(this, "Thêm sách thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
           layThongTinSach();
          
       }
           
       
       luu.close();
       ketNoi.close();
        
        
        
        }catch(SQLException e){
            System.out.println("Loi khong ket noi SQL");
        }
        
        
        
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed

        int selectedRow = jTableBangSach.getSelectedRow();

        if (selectedRow == -1) { // Nếu không có hàng nào được chọn
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng để sửa!");
            return;
        }

        // Lấy dữ liệu hiện tại của hàng được chọn
        String maSach = (String) jTableBangSach.getValueAt(selectedRow, 0); // Cột MASACH
        String tuaSach = (String) jTableBangSach.getValueAt(selectedRow, 1); // Cột TUASACH
        String tacGia = (String) jTableBangSach.getValueAt(selectedRow, 2); // Cột TACGIA
        String nhaXuatBan = (String) jTableBangSach.getValueAt(selectedRow, 3); // Cột NHAXUATBAN

        // Hiển thị hộp thoại để nhập dữ liệu mới
        String suaTuaSach = JOptionPane.showInputDialog(null, "Nhập tựa sách mới:", tuaSach);
        if (suaTuaSach == null || suaTuaSach.trim().isEmpty()) return;

        String suaTacGia = JOptionPane.showInputDialog(null, "Nhập tác giả mới:", tacGia);
        if (suaTacGia == null || suaTacGia.trim().isEmpty()) return;

        String suaNhaXuatBan = JOptionPane.showInputDialog(null, "Nhập nhà xuất bản mới:", nhaXuatBan);
        if (suaNhaXuatBan == null || suaNhaXuatBan.trim().isEmpty()) return;

        // Cập nhật thông tin trong cơ sở dữ liệu
        Connection ketNoi = KetNoiCSDL.layKetNoi();
        String sql = "UPDATE SACH SET TUASACH = ?, TACGIA = ?, NHAXUATBAN = ? WHERE MASACH = ?";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1, suaTuaSach); // Giá trị mới cho cột TUASACH
            ps.setString(2, suaTacGia); // Giá trị mới cho cột TACGIA
            ps.setString(3, suaNhaXuatBan); // Giá trị mới cho cột NHAXUATBAN
            ps.setString(4, maSach); // Điều kiện WHERE với MASACH
            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Sửa thành công!");

                // Cập nhật giao diện bảng
                DefaultTableModel model = (DefaultTableModel) jTableBangSach.getModel();
                model.setValueAt(suaTuaSach, selectedRow, 1); // Cột TUASACH
                model.setValueAt(suaTacGia, selectedRow, 2); // Cột TACGIA
                model.setValueAt(suaNhaXuatBan, selectedRow, 3); // Cột NHAXUATBAN
            } else {
                JOptionPane.showMessageDialog(null, "Không tìm thấy sách để sửa!");
            }

            ps.close();
            ketNoi.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khi sửa sách: " + ex.getMessage());
        }
    
        
        
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonXoaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonXoaMouseClicked

    public void layThongTinSach(){
        DefaultTableModel bang = (DefaultTableModel) jTableBangSach.getModel();
        bang.setRowCount(0);
        
        Connection ketNoi = KetNoiCSDL.layKetNoi();
        String laySach = "select * from SACH";
        
        Vector vt;
        try{
            Statement luuSach = ketNoi.createStatement();
            ResultSet rs = luuSach.executeQuery(laySach);
            
            while(rs.next()){
                vt = new Vector();
                vt.add(rs.getString("MASACH"));
                vt.add(rs.getString("TUASACH"));
                vt.add(rs.getString("TACGIA"));
                vt.add(rs.getString("NHAXUATBAN"));
                bang.addRow(vt);
            }
            jTableBangSach.setModel(bang);
          System.out.println("Lay thong tin sach thanh cong!");
          rs.close();
          luuSach.close();
          ketNoi.close();
     
        } catch (SQLException e){
            System.out.println("Loi ket noi SQL");
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSV2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLamLai;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JLabel jLabelChucNang;
    private javax.swing.JLabel jLabelMaSach1;
    private javax.swing.JLabel jLabelNXB;
    private javax.swing.JLabel jLabelTacGia;
    private javax.swing.JLabel jLabelThongTin1;
    private javax.swing.JLabel jLabelTieuDe;
    private javax.swing.JLabel jLabelTuaSach;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBangSach;
    private javax.swing.JTextField jTextFieldMaSach;
    private javax.swing.JTextField jTextFieldNXB;
    private javax.swing.JTextField jTextFieldTacGia;
    private javax.swing.JTextField jTextFieldTuaSach;
    // End of variables declaration//GEN-END:variables
}
