/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlsach;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ddoox
 */
public class QLSach extends javax.swing.JFrame {

    /**
     * Creates new form QLSach
     */
    public QLSach() {
        initComponents();
        layThongTinDauSach();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_MaSach = new javax.swing.JTextField();
        jTextField_TacGia = new javax.swing.JTextField();
        jTextField_TuaSach = new javax.swing.JTextField();
        jTextField_NXB = new javax.swing.JTextField();
        jButton_Them = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jButton_LamLai = new javax.swing.JButton();
        jButton_Thoat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSach = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Thông tin");

        jLabel2.setText("Mã sách");

        jLabel3.setText("Tác giả");

        jLabel4.setText("Tựa sách");

        jLabel5.setText("Nhà xuất bản");

        jLabel6.setText("Chức năng");

        jButton_Them.setText("Thêm");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });

        jButton_Sua.setText("Sửa");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });

        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        jButton_LamLai.setText("Làm lại");
        jButton_LamLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LamLaiActionPerformed(evt);
            }
        });

        jButton_Thoat.setText("Thoát");
        jButton_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_TuaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_MaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Them)
                                .addGap(38, 38, 38)
                                .addComponent(jButton_Sua)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_NXB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jButton_Xoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jButton_LamLai)
                                .addGap(31, 31, 31)
                                .addComponent(jButton_Thoat)))))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_MaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_TuaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_NXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Them)
                    .addComponent(jButton_Sua)
                    .addComponent(jButton_LamLai)
                    .addComponent(jButton_Xoa)
                    .addComponent(jButton_Thoat))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTableSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tựa sách", "Tác giả", "NXB"
            }
        ));
        jScrollPane2.setViewportView(jTableSach);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        // TODO add your handling code here:
        String maSach = jTextField_MaSach.getText().trim();
        String tacGia = jTextField_TacGia.getText().trim();
        String tuaSach = jTextField_TuaSach.getText().trim();
        String nxb = jTextField_NXB.getText().trim();
        
        if (maSach.isEmpty() || tacGia.isEmpty() || tuaSach.isEmpty() || nxb.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin sách.");
            return; // Exit the method if inputs are not valid
        }


        // Step 4: Connect to the database and execute the SQL statement
        Connection ketNoi = KetNoiCSDL.layKetNoi();
        try {
        // Step 2: Check if the book ID already exists
        String checkSql = "SELECT COUNT(*) FROM SACH WHERE MASACH = ?";
        try (PreparedStatement checkStmt = ketNoi.prepareStatement(checkSql)) {
            checkStmt.setString(1, maSach);
            ResultSet rs = checkStmt.executeQuery();
            if (rs.next() && rs.getInt(1) > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Mã sách đã tồn tại. Không thể thêm sách mới!");
                return; // Exit if the book ID already exists
            }
        }

        // Step 3: If not exists, insert the new book
        String insertSql = "INSERT INTO SACH (MASACH, TUASACH, TACGIA, NHAXUATBAN) VALUES (?, ?, ?, ?)";
            try (PreparedStatement insertStmt = ketNoi.prepareStatement(insertSql)) {
                insertStmt.setString(1, maSach);
                insertStmt.setString(2, tuaSach);
                insertStmt.setString(3, tacGia);
                insertStmt.setString(4, nxb);
                int rowsAffected = insertStmt.executeUpdate();
                if (rowsAffected > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Thêm sách thành công!");
                    layThongTinDauSach(); // Refresh the data table
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Thêm sách không thành công!");
                }
            }
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi thêm sách: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            try {
                if (ketNoi != null && !ketNoi.isClosed()) {
                    ketNoi.close();
                }
            } catch (SQLException ex) {
                System.out.println("Lỗi đóng kết nối cơ sở dữ liệu");
            }
        }
    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jButton_LamLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LamLaiActionPerformed
        // TODO add your handling code here:
        jTextField_MaSach.setText("");  // Xóa ô nhập mã sách
        jTextField_TuaSach.setText("");  // Xóa ô nhập tên sách
        jTextField_TacGia.setText("");  // Xóa ô nhập tên tác giả
        jTextField_NXB.setText("");

        // Gọi lại phương thức lấy thông tin đầu sách (ví dụ)
        layThongTinDauSach();
    }//GEN-LAST:event_jButton_LamLaiActionPerformed

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        // TODO add your handling code here:
        String maSach = jTextField_MaSach.getText().trim();
        String tacGia = jTextField_TacGia.getText().trim();
        String tuaSach = jTextField_TuaSach.getText().trim();
        String nxb = jTextField_NXB.getText().trim();

        // Kiểm tra nếu mã sách trống
        if (maSach.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sách để sửa.");
            return; // Thoát khỏi phương thức nếu mã sách trống
        }

        // Kết nối đến cơ sở dữ liệu
        Connection ketNoi = KetNoiCSDL.layKetNoi();
        try {
            // Bước 1: Kiểm tra xem mã sách có tồn tại trong database không
            String checkSql = "SELECT COUNT(*) FROM SACH WHERE MASACH = ?";
            try (PreparedStatement checkStmt = ketNoi.prepareStatement(checkSql)) {
                checkStmt.setString(1, maSach);
                ResultSet rs = checkStmt.executeQuery();
                if (rs.next() && rs.getInt(1) == 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Mã sách không tồn tại. Không thể sửa!");
                    return; // Thoát nếu mã sách không tồn tại
                }
            }

            // Bước 2: Xây dựng câu lệnh UPDATE động tùy thuộc vào các trường nhập
            StringBuilder updateSql = new StringBuilder("UPDATE SACH SET ");
            boolean hasUpdate = false; // Biến kiểm tra có cột nào được sửa hay không

            if (!tuaSach.isEmpty()) {
                updateSql.append("TUASACH = ?, ");
                hasUpdate = true;
            }
            if (!tacGia.isEmpty()) {
                updateSql.append("TACGIA = ?, ");
                hasUpdate = true;
            }
            if (!nxb.isEmpty()) {
                updateSql.append("NHAXUATBAN = ?, ");
                hasUpdate = true;
            }

            // Nếu không có gì để sửa, thông báo và thoát
            if (!hasUpdate) {
                javax.swing.JOptionPane.showMessageDialog(this, "Không có thông tin nào để sửa.");
                return;
            }

            // Loại bỏ dấu phẩy thừa cuối câu lệnh
            updateSql.setLength(updateSql.length() - 2);
            updateSql.append(" WHERE MASACH = ?");

            // Bước 3: Thực thi câu lệnh UPDATE
            try (PreparedStatement updateStmt = ketNoi.prepareStatement(updateSql.toString())) {
                int paramIndex = 1;

                // Gắn giá trị tham số vào câu lệnh SQL
                if (!tuaSach.isEmpty()) {
                    updateStmt.setString(paramIndex++, tuaSach);
                }
                if (!tacGia.isEmpty()) {
                    updateStmt.setString(paramIndex++, tacGia);
                }
                if (!nxb.isEmpty()) {
                    updateStmt.setString(paramIndex++, nxb);
                }
                updateStmt.setString(paramIndex, maSach); // Mã sách ở cuối câu lệnh

                int rowsAffected = updateStmt.executeUpdate();
                if (rowsAffected > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật sách thành công!");
                    layThongTinDauSach(); // Làm mới bảng dữ liệu
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật sách không thành công!");
                }
            }
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi sửa sách: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            try {
                if (ketNoi != null && !ketNoi.isClosed()) {
                    ketNoi.close();
                }
            } catch (SQLException ex) {
                System.out.println("Lỗi đóng kết nối cơ sở dữ liệu");
            }
        }
    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        // TODO add your handling code here:
        String maSach = jTextField_MaSach.getText().trim();

        // Kiểm tra nếu mã sách trống
        if (maSach.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sách để xóa.");
            return; // Thoát nếu mã sách trống
        }

        // Kết nối đến cơ sở dữ liệu
        Connection ketNoi = KetNoiCSDL.layKetNoi();
        try {
            // Bước 1: Kiểm tra xem mã sách có tồn tại trong database không
            String checkSql = "SELECT COUNT(*) FROM SACH WHERE MASACH = ?";
            try (PreparedStatement checkStmt = ketNoi.prepareStatement(checkSql)) {
                checkStmt.setString(1, maSach);
                ResultSet rs = checkStmt.executeQuery();
                if (rs.next() && rs.getInt(1) == 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Mã sách không tồn tại. Không thể xóa!");
                    return; // Thoát nếu mã sách không tồn tại
                }
            }

            // Bước 2: Xóa sách theo mã sách
            String deleteSql = "DELETE FROM SACH WHERE MASACH = ?";
            try (PreparedStatement deleteStmt = ketNoi.prepareStatement(deleteSql)) {
                deleteStmt.setString(1, maSach);
                int rowsAffected = deleteStmt.executeUpdate();
                if (rowsAffected > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Xóa sách thành công!");
                    layThongTinDauSach(); // Làm mới bảng dữ liệu
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Xóa sách không thành công!");
                }
            }
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi xóa sách: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            try {
                if (ketNoi != null && !ketNoi.isClosed()) {
                    ketNoi.close();
                }
            } catch (SQLException ex) {
                System.out.println("Lỗi đóng kết nối cơ sở dữ liệu");
            }
        }
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jButton_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThoatActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Bạn có chắc chắn muốn thoát chương trình?", 
            "Xác nhận thoát", 
            javax.swing.JOptionPane.YES_NO_OPTION);

        // Nếu người dùng chọn "Yes", thoát chương trình
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0); // Thoát chương trình
        }
    }//GEN-LAST:event_jButton_ThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    private void layThongTinDauSach() {
        DefaultTableModel dtm = (DefaultTableModel) jTableSach.getModel();
        dtm.setRowCount(0); // Uncomment this line if you want to clear old data on the table.

        Connection ketNoi = KetNoiCSDL.layKetNoi(); // Assuming the method is in a class called KetNoiCSDL.
        String sql = "SELECT * FROM SACH";
        Vector vt;

        try (
            Statement ps = ketNoi.createStatement();
            ResultSet rs = ps.executeQuery(sql)
        ) {
            while (rs.next()) {
                vt = new Vector();
                vt.add(rs.getString("MASACH"));
                vt.add(rs.getString("TUASACH"));
                vt.add(rs.getString("TACGIA"));
                vt.add(rs.getString("NHAXUATBAN"));
                dtm.addRow(vt);
            }
            jTableSach.setModel(dtm);
        } catch (SQLException ex) {
            System.out.println("Loi khi doc du lieu tu bang Sach");
            ex.printStackTrace(); // For debugging.
        } finally {
            try {
                if (ketNoi != null && !ketNoi.isClosed()) {
                    ketNoi.close();
                }
            } catch (SQLException ex) {
                System.out.println("loi doc du lieu");        }
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_LamLai;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_Thoat;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableSach;
    private javax.swing.JTextField jTextField_MaSach;
    private javax.swing.JTextField jTextField_NXB;
    private javax.swing.JTextField jTextField_TacGia;
    private javax.swing.JTextField jTextField_TuaSach;
    // End of variables declaration//GEN-END:variables
}
